### ISSUE TITLE
Lombok configuration should be in authentication-and-security

### ISSUE THREAD

**Issue by yurii-luchkiv** [vitaliy-denys/java-temple#1]
Hi 

lombok.config should be present in authentication-and-security 😜

Would it be possible to fix this? 

Thanks)))

**Comment by pavlo-pastushok** [comment]
Hi, Vitaliy 😄

I completely agree with Yurii.

Can you, please, provide a little bit more readable README file, please?

Thanks

**Comment by vitaliy-denys** [comment]
Thank you guys 😄
